server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost

spring:
  application.name: eureka
  output.ansi.enabled: always
  cloud.config.uri: ${CONFIG_SERVER_URL:http://localhost:8888}