spring:
  application.name: HelloClient
  output.ansi.enabled: always

server:
  port: 7211

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false